language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t aidasb/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true aidasb/react-test npm test

after_success:
  - docker build -t aidasb/multi-client ./client
  - docker build -t aidasb/multi-nginx ./nginx
  - docker build -t aidasb/multi-server ./server
  - docker build -t aidasb/multi-worker ./worker
#login to docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
#push images to docker hub
  - docker push aidasb/multi-client
  - docker push aidasb/multi-nginx
  - docker push aidasb/multi-server
  - docker push aidasb/multi-worker